name: CI CD

on:
  push:
    branches:
      - master

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - uses: actions/setup-node@v2
      with:
        node-version: '12'

    - name: Install dependencies
      run:
        npm install


    - name: build
      run:
        npm build

    - name: upload artifact
      uses: actions/upload-artifact@master
      with:
        name: build
        path: build
        
  deploy:
    needs: build

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: download artifact
        uses: actions/download-artifact@master
        with:
          name: build

      - name: deploy to S3
        run: |
          aws s3 rm s3://jr-lms-demo --recursive
          aws s3 cp . s3://jr-lms-demo/ --recursive
        env:
          AWS_DEFAULT_REGION: ap-southeast-2
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
